@ExpenseTrackerAPI_HostAddress = http://localhost:5181

###
# Get all expenses
GET {{ExpenseTrackerAPI_HostAddress}}/api/expenses/
Accept: application/json

###
# Get a single expense by ID
GET {{ExpenseTrackerAPI_HostAddress}}/api/expenses/2
Accept: application/json

###
# Add a new expense
POST {{ExpenseTrackerAPI_HostAddress}}/api/expenses/
Content-Type: application/json
{
  "name": "Tutorial Book",
  "amount": 30.00
}

###
# Update an existing expense
PUT {{ExpenseTrackerAPI_HostAddress}}/api/expenses/2
Content-Type: application/json
{
  "id": 2,
  "name": "Phone",
  "amount": 400.00
}